name: Generate and Deploy DocC

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Swift
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
          
      - name: Build DocC
        run: |
          swift package --allow-writing-to-directory ./docs-out \
            generate-documentation --target anilist \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path anilist-sdk \
            --output-path ./docs-out
            
          echo "<!DOCTYPE html><html><head><meta http-equiv=\"refresh\" content=\"0; url=/anilist-sdk/documentation/anilist\"></head><body></body></html>" > ./docs-out/index.html
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs-out'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
